info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      operationId: helloWorld
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello world
      tags:
      - example
swagger: "2.0"
